;; NFT-Based Virtual Concert Ticketing Smart Contract
;; Implements SIP-009 NFT standard with anti-scalping mechanisms

(define-non-fungible-token concert-ticket uint)

(define-constant contract-owner tx-sender)
(define-constant err-owner-only (err u100))
(define-constant err-not-token-owner (err u101))
(define-constant err-not-found (err u102))
(define-constant err-burn-failed (err u103))
(define-constant err-scalping-detected (err u104))
(define-constant err-invalid-price (err u105))
(define-constant err-invalid-royalty (err u106))
(define-constant err-transfer-failed (err u107))
(define-constant err-unauthorized (err u108))
(define-constant err-event-ended (err u109))
(define-constant max-scalping-price u500)
(define-constant default-royalty-rate u5)
(define-constant max-royalty-rate u25)

(define-data-var last-token-id uint u0)

(define-map token-owners uint principal)
(define-map token-uris uint (optional (string-ascii 256)))
(define-map token-prices uint uint)
(define-map token-purchase-blocks uint uint)
(define-map token-resale-count uint uint)
(define-map event-details uint {artist: principal, venue: (string-ascii 100), event-date: uint, max-tickets: uint, base-price: uint, royalty-rate: uint})
(define-map event-ticket-count uint uint)
(define-map authorized-minters principal bool)
(define-map burned-tokens uint bool)

(define-public (get-last-token-id)
  (ok (var-get last-token-id)))

(define-public (get-token-uri (token-id uint))
  (ok (map-get? token-uris token-id)))

(define-public (get-owner (token-id uint))
  (ok (nft-get-owner? concert-ticket token-id)))

(define-public (transfer (token-id uint) (sender principal) (recipient principal))
  (begin
    (asserts! (is-eq tx-sender sender) err-not-token-owner)
    (asserts! (is-eq (some sender) (nft-get-owner? concert-ticket token-id)) err-not-token-owner)
    (asserts! (not (default-to false (map-get? burned-tokens token-id))) err-not-found)
    (let ((event-id (get-event-id-from-token token-id))
          (event-info (unwrap! (map-get? event-details event-id) err-not-found))
          (royalty-amount (/ (* (default-to u0 (map-get? token-prices token-id)) (get royalty-rate event-info)) u100))
          (artist (get artist event-info)))
      (if (> royalty-amount u0)
          (try! (stx-transfer? royalty-amount sender artist))
          true)
      (map-set token-resale-count token-id (+ (default-to u0 (map-get? token-resale-count token-id)) u1))
      (nft-transfer? concert-ticket token-id sender recipient))))

(define-public (create-event (event-id uint) (venue (string-ascii 100)) (event-date uint) (max-tickets uint) (base-price uint) (royalty-rate uint))
  (begin
    (asserts! (is-eq tx-sender contract-owner) err-owner-only)
    (asserts! (<= royalty-rate max-royalty-rate) err-invalid-royalty)
    (asserts! (> event-date (default-to u0 (get-stacks-block-info? time (- stacks-block-height u1)))) err-event-ended)
    (map-set event-details event-id {artist: tx-sender, venue: venue, event-date: event-date, max-tickets: max-tickets, base-price: base-price, royalty-rate: royalty-rate})
    (map-set event-ticket-count event-id u0)
    (ok event-id)))

(define-public (mint-ticket (event-id uint) (recipient principal) (token-uri (optional (string-ascii 256))))
  (let ((event-info (unwrap! (map-get? event-details event-id) err-not-found))
        (current-count (default-to u0 (map-get? event-ticket-count event-id)))
        (new-token-id (+ (var-get last-token-id) u1)))
    (asserts! (or (is-eq tx-sender contract-owner) (is-eq tx-sender (get artist event-info)) (default-to false (map-get? authorized-minters tx-sender))) err-unauthorized)
    (asserts! (< current-count (get max-tickets event-info)) err-not-found)
    (try! (nft-mint? concert-ticket new-token-id recipient))
    (map-set token-uris new-token-id token-uri)
    (map-set token-prices new-token-id (get base-price event-info))
    (map-set token-purchase-blocks new-token-id stacks-block-height)
    (map-set event-ticket-count event-id (+ current-count u1))
    (var-set last-token-id new-token-id)
    (ok new-token-id)))

(define-public (set-token-price (token-id uint) (new-price uint))
  (let ((owner (unwrap! (nft-get-owner? concert-ticket token-id) err-not-found)))
    (asserts! (is-eq tx-sender owner) err-not-token-owner)
    (asserts! (not (default-to false (map-get? burned-tokens token-id))) err-not-found)
    (map-set token-prices token-id new-price)
    (ok true)))

(define-public (buy-ticket (token-id uint) (max-price uint))
  (let ((owner (unwrap! (nft-get-owner? concert-ticket token-id) err-not-found))
        (price (default-to u0 (map-get? token-prices token-id)))
        (event-id (get-event-id-from-token token-id))
        (event-info (unwrap! (map-get? event-details event-id) err-not-found))
        (base-price (get base-price event-info))
        (royalty-amount (/ (* price (get royalty-rate event-info)) u100))
        (seller-amount (- price royalty-amount))
        (artist (get artist event-info)))
    (asserts! (not (default-to false (map-get? burned-tokens token-id))) err-not-found)
    (asserts! (<= price max-price) err-invalid-price)
    (if (> price (* base-price max-scalping-price))
        (try! (burn-scalped-ticket token-id))
        true)
    (try! (stx-transfer? seller-amount tx-sender owner))
    (if (> royalty-amount u0)
        (try! (stx-transfer? royalty-amount tx-sender artist))
        true)
    (map-set token-resale-count token-id (+ (default-to u0 (map-get? token-resale-count token-id)) u1))
    (nft-transfer? concert-ticket token-id owner tx-sender)))

(define-public (burn-scalped-ticket (token-id uint))
  (let ((owner (unwrap! (nft-get-owner? concert-ticket token-id) err-not-found))
        (price (default-to u0 (map-get? token-prices token-id)))
        (event-id (get-event-id-from-token token-id))
        (event-info (unwrap! (map-get? event-details event-id) err-not-found))
        (base-price (get base-price event-info))
        (resale-count (default-to u0 (map-get? token-resale-count token-id))))
    (asserts! (or (is-eq tx-sender contract-owner) (> price (* base-price max-scalping-price)) (> resale-count u3)) err-scalping-detected)
    (try! (nft-burn? concert-ticket token-id owner))
    (map-set burned-tokens token-id true)
    (ok true)))

(define-public (authorize-minter (minter principal))
  (begin
    (asserts! (is-eq tx-sender contract-owner) err-owner-only)
    (map-set authorized-minters minter true)
    (ok true)))

(define-public (revoke-minter (minter principal))
  (begin
    (asserts! (is-eq tx-sender contract-owner) err-owner-only)
    (map-delete authorized-minters minter)
    (ok true)))

(define-read-only (get-token-price (token-id uint))
  (map-get? token-prices token-id))

(define-read-only (get-event-info (event-id uint))
  (map-get? event-details event-id))

(define-read-only (get-ticket-count (event-id uint))
  (default-to u0 (map-get? event-ticket-count event-id)))

(define-read-only (get-resale-count (token-id uint))
  (default-to u0 (map-get? token-resale-count token-id)))

(define-read-only (is-token-burned (token-id uint))
  (default-to false (map-get? burned-tokens token-id)))

(define-read-only (get-purchase-block (token-id uint))
  (map-get? token-purchase-blocks token-id))

(define-read-only (is-authorized-minter (principal principal))
  (default-to false (map-get? authorized-minters principal)))

(define-private (get-event-id-from-token (token-id uint))
  (/ token-id u1000))
